### PR TITLE
Add some mill repos

### PR DESCRIPTION
**Pull request by joan38**
- mill-tpolecat (cc @DavidGregory084)
- mill-git
- mill-scalafix
- kafka-streams-circe
- kubernetes-client

### CODE REVIEW

**Comment by fthomas** [comment]
I'll be waiting for approval by @DavidGregory084 before merging.

**Comment by DavidGregory084** [comment]
Wow, I had no idea about the mill support 👍 Sounds great, please go ahead @fthomas

**Comment by fthomas** [comment]
@DavidGregory084 Scala Steward currently fails to load the build of mill-tpolecat:
```
'mill -i -p ~/scala-steward/workspace/repos/DavidGregory084/mill-tpolecat/scala-steward.sc show org.scalasteward.mill.plugin.StewardPlugin/extractDeps' exited with code 1
No mill version specified.
You should provide a version via '.mill-version' file or --mill-version option.
Using mill version 0.7.4
Compiling ~/scala-steward/workspace/repos/DavidGregory084/mill-tpolecat/scala-steward.sc
Downloading https://repo1.maven.org/maven2/de/tototec/de.tobiasroeser.mill.integrationtest_2.13/0.2.1/de.tobiasroeser.mill.integrationtest_2.13-0.2.1.pom
Downloaded https://repo1.maven.org/maven2/de/tototec/de.tobiasroeser.mill.integrationtest_2.13/0.2.1/de.tobiasroeser.mill.integrationtest_2.13-0.2.1.pom
Downloading https://repo1.maven.org/maven2/de/tototec/de.tobiasroeser.mill.integrationtest_2.13/0.2.1/de.tobiasroeser.mill.integrationtest_2.13-0.2.1.pom.sha1
Downloaded https://repo1.maven.org/maven2/de/tototec/de.tobiasroeser.mill.integrationtest_2.13/0.2.1/de.tobiasroeser.mill.integrationtest_2.13-0.2.1.pom.sha1
Downloading https://oss.sonatype.org/content/repositories/snapshots/de/tototec/de.tobiasroeser.mill.integrationtest_2.13/0.2.1/de.tobiasroeser.mill.integrationtest_2.13-0.2.1.pom
Downloaded https://oss.sonatype.org/content/repositories/snapshots/de/tototec/de.tobiasroeser.mill.integrationtest_2.13/0.2.1/de.tobiasroeser.mill.integrationtest_2.13-0.2.1.pom
Downloading https://oss.sonatype.org/content/repositories/snapshots/de/tototec/de.tobiasroeser.mill.integrationtest_2.13/0.2.1/de.tobiasroeser.mill.integrationtest_2.13-0.2.1.pom.sha1
Downloaded https://oss.sonatype.org/content/repositories/snapshots/de/tototec/de.tobiasroeser.mill.integrationtest_2.13/0.2.1/de.tobiasroeser.mill.integrationtest_2.13-0.2.1.pom.sha1
Failed to resolve ivy dependencies:Error downloading de.tototec:de.tobiasroeser.mill.integrationtest_2.13:0.2.1
  not found: ~/.ivy2/local/de.tototec/de.tobiasroeser.mill.integrationtest_2.13/0.2.1/ivys/ivy.xml
  not found: https://repo1.maven.org/maven2/de/tototec/de.tobiasroeser.mill.integrationtest_2.13/0.2.1/de.tobiasroeser.mill.integrationtest_2.13-0.2.1.pom
  not found: https://oss.sonatype.org/content/repositories/snapshots/de/tototec/de.tobiasroeser.mill.integrationtest_2.13/0.2.1/de.tobiasroeser.mill.integrationtest_2.13-0.2.1.pom
```

It is using https://github.com/lefou/millw as `mill` executable which uses the latest Mill version if none is specified via a `.mill-version` file. In this case it is using Mill 0.7.4 but it seems that mill-tpolecat requires Mill version 0.6.2. I think Scala Steward would succeed loading the build if you put a `.mill-version` file with the version 0.6.2 in that repo.

**Comment by joan38** [comment]
[mill-tpolecat](https://github.com/DavidGregory084/mill-tpolecat/pull/6) is using https://github.com/lefou/mill-integrationtest not https://github.com/lefou/millw.

Great catch, I've updated the plugin with https://github.com/DavidGregory084/mill-tpolecat/pull/6

**Comment by fthomas** [comment]
Sorry, I was unclear. I meant that Scala Steward uses lefou/millw as `mill` executable that is used to extract dependencies from the build. My thinking was that the mill-tpolecat build requires Mill 0.6.2 but since there is no `.mill-version` file, `mill` uses the latest version (0.7.4) and that fails.

**Comment by joan38** [comment]
Aaah I see.
I've added a `mill` script that contains the mill version to use, it acts the same as a `.mill-version` file.

**Comment by joan38** [comment]
I merged the PR.
Thanks @fthomas for reporting this!

**Comment by fthomas** [comment]
Not sure if it helps since Scala Steward will not use the script in the repo. I'll let you know what happens on the next Scala Steward run.

**Comment by joan38** [comment]
I think it does because in our private instance it failed on missing `curl` in the `./mill` script and that's why I PRed https://github.com/fthomas/scala-steward/pull/1526

**Comment by lefou** [comment]
> In any case even if you don't use the `./mill` script it will pick the version to use in it.

What you describe is correct for the `mill` shell script bundled with mill, but not for `millw` from https://github.com/lefou/millw. `.mill-version` is IMHO the best unique place where to put the preferred mill version.

**Comment by fthomas** [comment]
It is working now:
```
2020-07-14 22:13:01,403 INFO  ──────────── Steward DavidGregory084/mill-tpolecat ────────────
2020-07-14 22:13:01,403 INFO  Check cache of DavidGregory084/mill-tpolecat
2020-07-14 22:13:02,223 INFO  Refresh cache of DavidGregory084/mill-tpolecat
2020-07-14 22:13:30,863 INFO  Find updates for DavidGregory084/mill-tpolecat
2020-07-14 22:13:30,863 INFO  Found 0 updates
2020-07-14 22:13:30,863 INFO  DavidGregory084/mill-tpolecat is up-to-date
2020-07-14 22:13:30,880 INFO  ──────────── Total time: Steward DavidGregory084/mill-tpolecat: 29s 477ms ────────────
```

**Comment by joan38** [comment]
Nice 👍

**Pull request merged**
