### PR TITLE
Add profunktor/neutron

### PR DESCRIPTION
**Pull request by gvolpe**

### CODE REVIEW

**Comment by fthomas** [comment]
profunktor/neutron is a fork of cr-org/neutron which we're also tracking. Scala Steward gets confused if it tracks both: https://github.com/scala-steward-org/scala-steward/issues/1782. So I guess we should remove cr-org/neutron then.

**Comment by gvolpe** [comment]
Ah that's a fair point, @fthomas ! Okay I'll remove `cr-org/neutron` then, I already talked to my ex colleague before forking the project so I guess `profunktor/neutron` will be the default from now on.

**Comment by fthomas** [comment]
I just deleted @scala-steward's fork because profunktor/neutron received some PRs from Scala Steward that contained commits from cr-org/neutron. The next PRs should not contain any remnants from the upstream repo.

**Comment by gvolpe** [comment]
Thank you @fthomas !

**Pull request merged**
