### PR TITLE
remove old repo

### PR DESCRIPTION
**Pull request by hayssams**
This repo is now superseded by starlake-ai/starlake

### CODE REVIEW

**Comment by hayssams** [comment]
Hi Yasuhiro

Something strange is happening
Scala steward is checking my dependencies in starlake-ai/starlake but is
sending me PRs to the old repo ebiznext/comet-data-pipeline.
Best regards
Hayssam


Le mer. 13 oct. 2021 à 13:42, TATSUNO Yasuhiro ***@***.***> a
écrit :

**Comment by fthomas** [comment]
I deleted @scala-steward's old fork of ebiznext/comet-data-pipeline and hope this improves the situation.

**Comment by hayssams** [comment]
It worked.
Thank you !

**Comment by hayssams** [comment]
Euh no sorry.
It actually did not work.
I confused with starlake/starlake-api

**Comment by fthomas** [comment]
@hayssams Can you show me a PR where Scala Steward did something wrong? I can then better identify which fork needs to be deleted.

**Comment by hayssams** [comment]
Below a couple of screenshots
Notice that I receive the required updates for another project (starlake-ai/starlake-api) but not for starlake-ai/starlake.
Thank you

**Pull request merged**
