### PR TITLE
Maybe casing matters?

### PR DESCRIPTION
**Pull request by Qi77Qi**
haven't got a PR from scala-steward since yesterday's PR merge...updating casing to see if it changes anything

### CODE REVIEW

**Comment by fthomas** [comment]
I can take a look at the logs later to see what's wrong.

**Comment by fthomas** [comment]
Scala Steward can't clone the submodules in that repo:
```
java.io.IOException: 'COURSIER_PROGRESS=false SBT_OPTS=-Xmx2048m -Xss8m -XX:MaxMetaspaceSize=512m git clone --recursive https://scala-steward@github.com/scala-steward/leonardo.git /scala-steward/workspace/repos/DataBiosphere/leonardo' exited with code 1
Cloning into '/scala-steward/workspace/repos/DataBiosphere/leonardo'...
Submodule 'jenkins/dataproc-custom-images/dataproc-custom-images' (https://github.com/GoogleCloudPlatform/dataproc-custom-images.git) registered for path 'jenkins/dataproc-custom-images/dataproc-custom-images'
Submodule 'jenkins/gce-custom-images/cis-harden-images' (https://github.com/broadinstitute/dsp-appsec-base-image-hardening.git) registered for path 'jenkins/gce-custom-images/cis-harden-images'
Submodule 'jenkins/gce-custom-images/terra-cryptomining-security-alerts' (git@github.com:broadinstitute/terra-cryptomining-security-alerts.git) registered for path 'jenkins/gce-custom-images/terra-cryptomining-security-alerts'
Cloning into '/scala-steward/workspace/repos/DataBiosphere/leonardo/jenkins/dataproc-custom-images/dataproc-custom-images'...
Cloning into '/scala-steward/workspace/repos/DataBiosphere/leonardo/jenkins/gce-custom-images/cis-harden-images'...
Cloning into '/scala-steward/workspace/repos/DataBiosphere/leonardo/jenkins/gce-custom-images/terra-cryptomining-security-alerts'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:broadinstitute/terra-cryptomining-security-alerts.git' into submodule path '/scala-steward/workspace/repos/DataBiosphere/leonardo/jenkins/gce-custom-images/terra-cryptomining-security-alerts' failed
Failed to clone 'jenkins/gce-custom-images/terra-cryptomining-security-alerts'. Retry scheduled
Cloning into '/scala-steward/workspace/repos/DataBiosphere/leonardo/jenkins/gce-custom-images/terra-cryptomining-security-alerts'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:broadinstitute/terra-cryptomining-security-alerts.git' into submodule path '/scala-steward/workspace/repos/DataBiosphere/leonardo/jenkins/gce-custom-images/terra-cryptomining-security-alerts' failed
Failed to clone 'jenkins/gce-custom-images/terra-cryptomining-security-alerts' a second time, aborting
```

**Comment by Qi77Qi** [comment]
I see...yea `git@github.com:broadinstitute/terra-cryptomining-security-alerts.git` is a private repo, is there a way to tell scala-steward to ignore this directory? 🤔

**Comment by fthomas** [comment]
No, there isn't. But we could change Scala Steward to ignore errors while cloning submodules.

**Comment by Qi77Qi** [comment]
that would be nice!...in our case, we don't care about these submodules at all. They're not scala repos

**Comment by fthomas** [comment]
Ok. Let's see if https://github.com/scala-steward-org/scala-steward/pull/1779 improves things.

**Comment by Qi77Qi** [comment]
@fthomas would you be able to give me write permission to https://github.com/scala-steward/leonardo? I'm not seeing update PRs from scala-steward for this repo. I can try to fix some PRs from scala-steward manually.

**Comment by fthomas** [comment]
@Qi77Qi Scala Steward keeps its forks in sync with the upstream repo automatically and it also allows maintainers of the forked repo to push to its update branches. So if there is a PR that you want to fix manually, you can already push fixes to its branch.

**Comment by Qi77Qi** [comment]
@Qi77Qi oh great...I thought I get permission denied. But it might be something else...Will try again when I need to

**Pull request merged**
